/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamenParcial;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author T-107
 */
public class PresentacionExamen extends javax.swing.JFrame {
    JRadioButton radios[];
    Opcion[] opciones,opciones1;
    Pregunta p1, p2;
    /**
     * Creates new form PresentacionExamen
     */
    public PresentacionExamen() {
        initComponents();
        setLocationRelativeTo(this);
        
        radios=new JRadioButton[4];
        radios[0]=RadioOP1;
        radios[1]=RadioOP2;
        radios[2]=RadioOP3;
        radios[3]=RadioOP4;
        
        opciones=new Opcion[4];
        Opcion op1=new Opcion("El Popocatepetl",false);
        Opcion op2=new Opcion("El Everest",true);
        Opcion op3=new Opcion("El Aconcagua",false);
        Opcion op4=new Opcion("El Pico de Orizaba",false);
        opciones[0]=op1;
        opciones[1]=op2;
        opciones[2]=op3;
        opciones[3]=op4;
        
        p1=new Pregunta("Cual es la montaña mas alta del mundo",opciones);
        EtiquetaPregunta.setText(p1.titulo);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(p1.opciones[i].titulo);
        }
        
        /*
        radios=new JRadioButton[4];
        radios[0]=RadioOP1;
        radios[1]=RadioOP2;
        radios[2]=RadioOP3;
        radios[3]=RadioOP4;
        
        opciones1=new Opcion[4];
        Opcion op11=new Opcion("Jalisco",false);
        Opcion op12=new Opcion("Michoacan",false);
        Opcion op13=new Opcion("Coahuila",true);
        Opcion op14=new Opcion("Tamaulipas",false);
        opciones1[0]=op11;
        opciones1[1]=op12;
        opciones1[2]=op13;
        opciones1[3]=op14;
        
        p2=new Pregunta("Todos los estados tienen costas excepto",opciones1);
        EtiquetaPregunta.setText(p2.titulo);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(p2.opciones1[i].titulo);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        EtiquetaPregunta = new javax.swing.JLabel();
        RadioOP1 = new javax.swing.JRadioButton();
        RadioOP2 = new javax.swing.JRadioButton();
        RadioOP3 = new javax.swing.JRadioButton();
        RadioOP4 = new javax.swing.JRadioButton();
        checar = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EtiquetaPregunta.setText("jLabel1");

        buttonGroup1.add(RadioOP1);
        RadioOP1.setText("jRadioButton1");

        buttonGroup1.add(RadioOP2);
        RadioOP2.setText("jRadioButton2");

        buttonGroup1.add(RadioOP3);
        RadioOP3.setText("jRadioButton3");

        buttonGroup1.add(RadioOP4);
        RadioOP4.setText("jRadioButton4");
        RadioOP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioOP4ActionPerformed(evt);
            }
        });

        checar.setText("Checar Respuesta");
        checar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RadioOP1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RadioOP2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RadioOP3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RadioOP4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(EtiquetaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(EtiquetaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioOP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioOP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioOP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioOP4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioOP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioOP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioOP4ActionPerformed

    private void checarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarActionPerformed
        // TODO add your handling code here:
        int IndiceSeleccionado=0;
        for(int i=0;i<radios.length;i++){
            if(radios[i].isSelected()){
                IndiceSeleccionado=i;
                break;
            }
        }
        JOptionPane.showConfirmDialog(this,""+evaluar(p1, IndiceSeleccionado));
    }//GEN-LAST:event_checarActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        radios=new JRadioButton[4];
        radios[0]=RadioOP1;
        radios[1]=RadioOP2;
        radios[2]=RadioOP3;
        radios[3]=RadioOP4;
        
        opciones=new Opcion[4];
        Opcion op1=new Opcion("Jalisco",false);
        Opcion op2=new Opcion("Michoacan",false);
        Opcion op3=new Opcion("Coahuila",true);
        Opcion op4=new Opcion("Tamaulipas",false);
        opciones[0]=op1;
        opciones[1]=op2;
        opciones[2]=op3;
        opciones[3]=op4;
        
        p1=new Pregunta("Todos los estados tiene costas excepto",opciones);
        EtiquetaPregunta.setText(p1.titulo);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(p1.opciones[i].titulo);
        } 
    }//GEN-LAST:event_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresentacionExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaPregunta;
    private javax.swing.JRadioButton RadioOP1;
    private javax.swing.JRadioButton RadioOP2;
    private javax.swing.JRadioButton RadioOP3;
    private javax.swing.JRadioButton RadioOP4;
    private javax.swing.JButton Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checar;
    // End of variables declaration//GEN-END:variables

    public boolean evaluar(Pregunta p, int IndiceSeleccionado){
        boolean correcta=false;
        if(p.opciones[IndiceSeleccionado].correcta){
            correcta=true;
        }
        return correcta;
    }
}
